create table public.roles_permissions (
  id uuid primary key default gen_random_uuid(),
  role public.app_role not null,
  module public.app_module not null,
  can_view boolean not null default false,
  can_create boolean not null default false,
  can_edit boolean not null default false,
  can_approve boolean not null default false,
  can_export boolean not null default false,
  unique (role, module)
);

insert into public.roles_permissions (role, module, can_view, can_create, can_edit, can_approve, can_export) values
('super_admin','daily_kpi',true,true,true,true,true),
('super_admin','nso_visit',true,true,true,true,true),
('super_admin','promotion_vm',true,true,true,true,true),
('super_admin','resolution',true,true,true,true,true),
('super_admin','lms',true,true,true,true,true),
('super_admin','coaching',true,true,true,true,true),
('management','daily_kpi',true,false,false,false,true),
('management','nso_visit',true,false,false,false,true),
('management','promotion_vm',true,false,false,false,true),
('management','resolution',true,false,false,true,true),
('management','lms',true,false,false,false,true),
('management','coaching',true,false,false,false,true),
('state_area_manager','daily_kpi',true,false,false,true,true),
('state_area_manager','nso_visit',true,false,false,true,true),
('state_area_manager','promotion_vm',true,false,false,false,true),
('state_area_manager','resolution',true,false,true,true,true),
('state_area_manager','lms',true,false,false,false,true),
('state_area_manager','coaching',true,false,false,false,true),
('nso','daily_kpi',true,false,false,true,true),
('nso','nso_visit',true,true,true,false,true),
('nso','promotion_vm',true,false,false,true,true),
('nso','resolution',true,true,true,false,true),
('nso','lms',true,false,false,false,false),
('nso','coaching',true,true,false,false,false),
('udc','daily_kpi',true,true,false,false,false),
('udc','nso_visit',true,true,false,false,false),
('udc','promotion_vm',true,true,false,false,false),
('udc','resolution',true,true,false,false,false),
('udc','lms',true,false,false,false,false),
('udc','coaching',true,false,false,false,false),
('dealer','daily_kpi',true,false,false,false,false),
('dealer','nso_visit',true,false,false,false,false),
('dealer','promotion_vm',true,false,false,false,false),
('dealer','resolution',true,false,false,false,false),
('dealer','lms',true,false,false,false,false),
('dealer','coaching',true,false,false,false,false),
('marketing_vm','daily_kpi',true,false,false,false,false),
('marketing_vm','nso_visit',true,false,false,false,false),
('marketing_vm','promotion_vm',true,true,true,true,true),
('marketing_vm','resolution',true,true,false,false,true),
('marketing_vm','lms',true,false,false,false,false),
('marketing_vm','coaching',true,false,false,false,false),
('training_admin','daily_kpi',true,false,false,false,false),
('training_admin','nso_visit',true,false,false,false,false),
('training_admin','promotion_vm',true,false,false,false,false),
('training_admin','resolution',true,false,false,false,false),
('training_admin','lms',true,true,true,true,true),
('training_admin','coaching',true,false,false,false,false),
('consultant','daily_kpi',true,false,false,false,true),
('consultant','nso_visit',true,false,false,false,true),
('consultant','promotion_vm',true,false,false,false,true),
('consultant','resolution',true,true,false,false,true),
('consultant','lms',true,false,false,false,false),
('consultant','coaching',true,true,true,false,true);
